shell scripts added for publishing packages

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,23 +1,26 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+# Check for changes in @playnest/configs
+CHANGED_CONFIGS=$(git diff --name-only HEAD~1 HEAD packages/configs/ | wc -l)
+if [ "$CHANGED_CONFIGS" -gt 0 ]; then
+  echo "❗Changes detected in @playnest/configs. Publishing is required"
+fi
+
 # Check for changes in @playnest/core
-CHANGED=$(git diff --name-only HEAD~1 HEAD packages/core/ | wc -l)
+CHANGED_CORE=$(git diff --name-only HEAD~1 HEAD packages/core/ | wc -l)
+if [ "$CHANGED_CORE" -gt 0 ]; then
+  echo "❗Changes detected in @playnest/core. Publishing is required"
+fi
 
-if [ "$CHANGED" -gt 0 ]; then
-  echo "🔍 Changes detected in @playnest/core. Launching publishing..."
+# Check for changes in @playnest/web
+CHANGED_WEB=$(git diff --name-only HEAD~1 HEAD packages/web/ | wc -l)
+if [ "$CHANGED_WEB" -gt 0 ]; then
+  echo "❗Changes detected in @playnest/web. Publishing is required"
+fi
 
-  echo "📦 Building..."
-  pnpm build --filter @playnest/core
 
-  cd packages/core || exit
-
-  echo "📤 Publishing to npm..."
-  npm publish
-
-  cd ../../
-
-  echo "✅ Published"
-else
-  echo "ℹ️ No changes in @playnest/core. Skipping publishing"
+if [ "$CHANGED_CONFIGS" -gt 0 ] || [ "$CHANGED_CORE" -gt 0 ] || [ "$CHANGED_WEB" -gt 0 ]; then
+  echo 'Run "pnpm push-publish" to push changes and publish packages'
+  exit 1
 fi
